accession: "config/accession_numbers.csv"
accession-covid: "config/covid_dataset.csv"

species:
  - "autographiviridae"
  - "demerecviridae_markadamsvirinae"
  - "drexlerviridae"
  - "myoviridae_ounavirinae"
  - "myoviridae_tevenvirinae"
  - "myoviridae_vequintavirinae_and_relatives"
  - "schitoviridae"
  - "siphoviridae_dhillonvirus"
  - "siphoviridae_queuovirinae_seuratvirus"
  - "siphoviridae_queuovirinae_sonagvirus"
  - "basel"

genome-comparison:
  mash-opt: "-k 15 -s 10000"

pangraph:
  kernel-options:
    std: "--circular -k minimap2 -s 20 -a 100 -b 10"
    20-20-5: "--circular -k minimap2 -s 20 -a 20 -b 5"
  polish-options: "-c"